"""add repo_name and user_id to repo_index table

Revision ID: 2f3e2d0f00a9
Revises: 5b309e9c0f8e
Create Date: 2026-06-22 14:40:17.258456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3e2d0f00a9'
down_revision: Union[str, Sequence[str], None] = '5b309e9c0f8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo_index', sa.Column('repo_name', sa.String(), nullable=False))
    op.add_column('repo_index', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'repo_index', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repo_index', type_='foreignkey')
    op.drop_column('repo_index', 'user_id')
    op.drop_column('repo_index', 'repo_name')
    # ### end Alembic commands ###
