"""add review_trace_id

Revision ID: 3ac6a33ca2ce
Revises: df3bbe5aebf3
Create Date: 2026-07-06 08:56:47.528650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ac6a33ca2ce'
down_revision: Union[str, Sequence[str], None] = 'df3bbe5aebf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('review_trace_id', sa.String(), nullable=True))
    op.add_column('review_feedback', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('review_feedback', sa.Column('review_trace_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'review_feedback', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review_feedback', type_='foreignkey')
    op.drop_column('review_feedback', 'review_trace_id')
    op.drop_column('review_feedback', 'user_id')
    op.drop_column('pull_requests', 'review_trace_id')
    # ### end Alembic commands ###
