"""remove repo_id columnm

Revision ID: 53ab996a89ce
Revises: f4d43f4f43aa
Create Date: 2026-06-16 11:05:02.303172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ab996a89ce'
down_revision: Union[str, Sequence[str], None] = 'f4d43f4f43aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_service_pair', 'added_repos', ['user_id', 'repo_name'])
    op.drop_column('added_repos', 'repo_id')
    op.drop_column('pull_requests', 'repo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('added_repos', sa.Column('repo_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_user_service_pair', 'added_repos', type_='unique')
    # ### end Alembic commands ###
