"""Add webhook_id column to added_repo table

Revision ID: 5b309e9c0f8e
Revises: 1c84f904a077
Create Date: 2026-06-19 16:29:22.299435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b309e9c0f8e'
down_revision: Union[str, Sequence[str], None] = '1c84f904a077'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('added_repos', sa.Column('webhook_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('added_repos', 'webhook_id')
    # ### end Alembic commands ###
