"""add review column to pr table and add index to repo_index table

Revision ID: a68269bafe50
Revises: 2f3e2d0f00a9
Create Date: 2026-06-24 12:12:45.859149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68269bafe50'
down_revision: Union[str, Sequence[str], None] = '2f3e2d0f00a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('review', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('idx_symbol_repo_name_user_id', 'repo_index', ['symbol', 'repo_name', 'user_id'], unique=False)
    op.create_unique_constraint('uq_user_service_pair_symbol', 'repo_index', ['user_id', 'repo_name', 'symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_service_pair_symbol', 'repo_index', type_='unique')
    op.drop_index('idx_symbol_repo_name_user_id', table_name='repo_index')
    op.drop_column('pull_requests', 'review')
    # ### end Alembic commands ###
