"""create review feedback table

Revision ID: b54511385b07
Revises: a68269bafe50
Create Date: 2026-07-05 15:00:38.215087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54511385b07'
down_revision: Union[str, Sequence[str], None] = 'a68269bafe50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_files_changed', sa.Integer(), nullable=False),
    sa.Column('total_lines_added', sa.Integer(), nullable=False),
    sa.Column('total_lines_deleted', sa.Integer(), nullable=False),
    sa.Column('total_delta', sa.Integer(), nullable=False),
    sa.Column('max_delta', sa.Integer(), nullable=False),
    sa.Column('avg_delta', sa.Integer(), nullable=False),
    sa.Column('changed_func_count', sa.Integer(), nullable=False),
    sa.Column('high_delta_count', sa.Integer(), nullable=False),
    sa.Column('risk_label', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_feedback_id'), 'review_feedback', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_feedback_id'), table_name='review_feedback')
    op.drop_table('review_feedback')
    # ### end Alembic commands ###
