"""add more pr features

Revision ID: d7a08da98268
Revises: 53ab996a89ce
Create Date: 2026-06-16 11:45:09.189176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a08da98268'
down_revision: Union[str, Sequence[str], None] = '53ab996a89ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pull_requests', sa.Column('status', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('title', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('body', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('url', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('pr_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'pr_id')
    op.drop_column('pull_requests', 'url')
    op.drop_column('pull_requests', 'body')
    op.drop_column('pull_requests', 'title')
    op.drop_column('pull_requests', 'status')
    # ### end Alembic commands ###
