"""[review_feedback] 
delete risk_score column and add is_trained column

Revision ID: df3bbe5aebf3
Revises: b54511385b07
Create Date: 2026-07-05 20:44:25.665048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3bbe5aebf3'
down_revision: Union[str, Sequence[str], None] = 'b54511385b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_feedback', sa.Column('is_trained', sa.Boolean(), nullable=False))
    op.drop_column('review_feedback', 'risk_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_feedback', sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('review_feedback', 'is_trained')
    # ### end Alembic commands ###
