"""add column name

Revision ID: f4d43f4f43aa
Revises: a35ae45c60ef
Create Date: 2026-06-16 10:02:13.321562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d43f4f43aa'
down_revision: Union[str, Sequence[str], None] = 'a35ae45c60ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('added_repos', sa.Column('repo_name', sa.String(), nullable=False))
    op.add_column('pull_requests', sa.Column('repo_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pull_requests', 'repo_name')
    op.drop_column('added_repos', 'repo_name')
    # ### end Alembic commands ###
